FROM node:16-alpine AS builder

COPY . /app

WORKDIR /app/demo-app

RUN npm install && npm run build

FROM node:16-alpine

WORKDIR /app

RUN npm install -g webserver.local

COPY --from=builder /app/demo-app/build ./build

CMD ["webserver.local", "-d", "./build"]

