FROM python:3-alpine AS builder

WORKDIR /app

COPY requirements.txt ./
RUN python3 -m venv venv
ENV PATH=/app/venv/bin/:$PATH

RUN pip install -r requirements.txt

COPY . ./

FROM gcr.io/distroless/python3

COPY --from=builder /app /app

WORKDIR /app

ENV PATH=/app/venv/bin/:$PATH

CMD ["app.py"]
