FROM python:3 AS builder

WORKDIR /app

ADD . /app

RUN pip3 install -r requirements.txt && \
    apt-get install binutils && \
    pip3 install pyinstaller && \
    pip3 install scons && \
    pip3 install patchelf && \
    pip3 install staticx

RUN pyinstaller app.py --onefile

RUN staticx /app/dist/app /app/statapp

FROM scratch

COPY --from=builder /app/statapp /

ADD tmp.tar /

CMD ["/statapp"]
